sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t kenansulayman/rtorrent-rutorrent-nightly .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push kenansulayman/rtorrent-rutorrent-nightly
